import { Component, EventEmitter, Input, OnInit, OnChanges, SimpleChanges, Output } from '@angular/core';
import { CourseService } from '../../services/course.service';
import { GroupService } from '../../services/group.service';
import { ToastService } from '../../services/toast.service';
import { ConfirmationService } from '../../services/confirmation.service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators, FormArray } from '@angular/forms';
import { debounceTime, distinctUntilChanged } from 'rxjs';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-group-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslateModule],
  template: `
    <div class="max-w-4xl mx-auto p-6">
      <div class="mb-6 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl shadow-xl p-8 text-white">
        <h1 class="text-3xl font-bold">{{ title }}</h1>
        <p class="text-indigo-100">{{ subtitle }}</p>
      </div>

      <form [formGroup]="form" (ngSubmit)="submit()" class="bg-white rounded-xl shadow-sm border border-gray-200">
        <div class="px-8 py-6 border-b border-gray-200">
          <h2 class="text-xl font-semibold text-gray-900">{{ 'groups.groupInformation' | translate }}</h2>
          <p class="mt-1 text-sm text-gray-600">{{ 'groups.fillInRequiredDetails' | translate }}</p>
        </div>

        <div class="p-8 space-y-6">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="form-label">
                {{ 'groups.name' | translate }} 
                <span class="text-xs text-gray-500 font-normal">({{ 'groups.autoGenerated' | translate }})</span>
              </label>
              <input class="form-input bg-gray-100 cursor-not-allowed" formControlName="name" [placeholder]="'groups.autoGeneratedPlaceholder' | translate" [disabled]="true" />
              <p class="text-xs text-gray-500 mt-1">
                <svg class="w-3 h-3 inline mr-1" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path>
                </svg>
                {{ 'groups.generatedFromCourseInfo' | translate }}
              </p>
            </div>
            <div>
              <label class="form-label">{{ 'groups.code' | translate }} <span class="text-xs text-gray-500 font-normal">({{ 'groups.autoGenerated' | translate }})</span></label>
              <input class="form-input bg-gray-100 cursor-not-allowed" formControlName="code" [placeholder]="'groups.codeAutoGenerated' | translate" [disabled]="true" />
              <p class="text-xs text-gray-500 mt-1">{{ 'groups.codeWillBeGenerated' | translate }}</p>
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="form-label">{{ 'groups.course' | translate }} <span class="text-red-500">*</span></label>
              <select class="form-input" formControlName="course">
                <option value="" disabled>{{ 'groups.selectCourse' | translate }}</option>
                <option *ngFor="let c of courses" [value]="c._id">
                  {{ c.name }} - {{ c.code }}
                </option>
              </select>
              <p class="text-xs text-gray-500 mt-1">
                {{ 'groups.teacherSubjectInherited' | translate }}
              </p>
            </div>
            <div>
              <label class="form-label">{{ 'groups.gradeLevel' | translate }} <span class="text-red-500">*</span></label>
              <select class="form-input" formControlName="gradeLevel">
                <option *ngFor="let g of grades" [value]="g">{{ g }}</option>
              </select>
            </div>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label class="form-label">{{ 'groups.pricePerSessionEGP' | translate }}</label>
              <input type="number" class="form-input" formControlName="pricePerSession" [placeholder]="'groups.egPlaceholder' | translate" />
            </div>
          </div>

          <!-- Display course info when selected -->
          <div *ngIf="selectedCourse" class="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h3 class="text-sm font-semibold text-blue-900 mb-2">{{ 'groups.courseInformation' | translate }}</h3>
            <div class="grid grid-cols-2 gap-3 text-sm">
              <div>
                <span class="text-blue-700 font-medium">{{ 'groups.teacher' | translate }}:</span>
                <span class="text-blue-900 ml-2">{{ selectedCourse.teacher?.fullName }}</span>
              </div>
              <div>
                <span class="text-blue-700 font-medium">{{ 'groups.subject' | translate }}:</span>
                <span class="text-blue-900 ml-2">{{ selectedCourse.subject?.name }}</span>
              </div>
            </div>
          </div>

          <!-- Weekly Schedule Section with Enhanced Styling -->
          <div class="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl border-2 border-indigo-200 p-6">
            <div class="flex items-center justify-between mb-4">
              <div class="flex items-center space-x-3">
                <div class="p-2 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-lg shadow-md">
                  <svg class="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                  </svg>
                </div>
                <div>
                  <h3 class="text-lg font-bold text-gray-900">{{ 'groups.weeklySchedule' | translate }}</h3>
                  <p class="text-xs text-gray-600">{{ 'groups.setUpClassTimings' | translate }}</p>
                </div>
              </div>
              <button type="button" (click)="addSlot()" class="btn-secondary inline-flex items-center text-sm shadow-md hover:shadow-lg transform hover:-translate-y-0.5 transition-all duration-200">
                <svg class="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path></svg>
                {{ 'groups.addTimeSlot' | translate }}
              </button>
            </div>
            
            <!-- Schedule Conflict Warning -->
            <div *ngIf="scheduleConflicts.length > 0" class="mb-4 p-4 bg-red-50 border-l-4 border-red-500 rounded-lg shadow-sm">
              <div class="flex items-start">
                <svg class="w-5 h-5 text-red-500 mr-2 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"/>
                </svg>
                <div class="flex-1">
                  <h4 class="text-sm font-semibold text-red-800 mb-1">{{ 'groups.scheduleConflictDetected' | translate }}</h4>
                  <p class="text-xs text-red-700 mb-2">{{ 'groups.teacherConflictingSchedules' | translate }}</p>
                  <ul class="space-y-1">
                    <li *ngFor="let conflict of scheduleConflicts" class="text-xs text-red-700">
                      <strong>{{ conflict.groupName }} ({{ conflict.groupCode }})</strong> - {{ conflict.day | titlecase }}: {{ conflict.time }}
                    </li>
                  </ul>
                </div>
              </div>
            </div>

            <div *ngIf="checkingConflicts" class="mb-4 p-3 bg-blue-50 border border-blue-200 rounded-lg text-sm text-blue-700 shadow-sm">
              <div class="flex items-center">
                <svg class="animate-spin h-4 w-4 mr-2" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                {{ 'groups.checkingScheduleConflicts' | translate }}
              </div>
            </div>
            
            <div formArrayName="schedule" class="space-y-3">
              <div *ngFor="let s of schedule.controls; let i = index" [formGroupName]="i" 
                   class="bg-white rounded-lg p-4 border border-indigo-200 shadow-sm hover:shadow-md transition-all duration-200">
                <div class="grid grid-cols-1 md:grid-cols-12 gap-3 items-end">
                  <div class="md:col-span-4">
                    <label class="text-xs font-medium text-gray-600 mb-1 block">{{ 'groups.day' | translate }}</label>
                    <select class="form-input" formControlName="day">
                      <option *ngFor="let d of days" [value]="d">{{ d | titlecase }}</option>
                    </select>
                  </div>
                  <div class="md:col-span-3">
                    <label class="text-xs font-medium text-gray-600 mb-1 block">{{ 'groups.startTime' | translate }}</label>
                    <input type="time" class="form-input" formControlName="startTime" placeholder="09:00" />
                  </div>
                  <div class="md:col-span-3">
                    <label class="text-xs font-medium text-gray-600 mb-1 block">{{ 'groups.endTime' | translate }}</label>
                    <input type="time" class="form-input" formControlName="endTime" placeholder="11:00" />
                  </div>
                  <div class="md:col-span-2">
                    <button type="button" (click)="removeSlot(i)" 
                            class="w-full px-3 py-2 text-sm font-medium text-red-700 bg-red-50 hover:bg-red-100 rounded-lg border border-red-200 transition-all duration-200 flex items-center justify-center">
                      <svg class="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                      </svg>
                      {{ 'groups.remove' | translate }}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-between items-center px-8 py-6 bg-gray-50 border-t border-gray-200">
          <button type="button" (click)="goBack()" class="btn-secondary inline-flex items-center">
            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>
            {{ 'groups.back' | translate }}
          </button>
          <div class="space-x-3">
            <button type="button" (click)="cancel.emit()" class="btn-secondary">{{ 'groups.cancel' | translate }}</button>
            <button type="submit" [disabled]="form.invalid || submitting" class="btn-primary">{{ submitText }}</button>
          </div>
        </div>
      </form>
    </div>
  `,
  styles: [`
    .form-label { @apply block text-sm font-semibold text-gray-700 mb-2; }
    .form-input { @apply w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition-all duration-200; }
    .btn-primary { @apply inline-flex items-center px-6 py-3 text-sm font-semibold rounded-lg text-white bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-700 hover:to-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed shadow-md hover:shadow-lg transition-all duration-200; }
    .btn-secondary { @apply inline-flex items-center px-6 py-3 border-2 border-gray-300 text-sm font-semibold rounded-lg text-gray-700 bg-white hover:bg-gray-50 transition-all duration-200; }
  `]
})
export class GroupFormComponent implements OnInit, OnChanges {
  @Input() initialValue: any = {};
  @Input() title = 'Add Group';
  @Input() subtitle = 'Create a weekly group with teacher, subject, and grade';
  @Input() submitText = 'Create Group';
  @Output() save = new EventEmitter<any>();
  @Output() cancel = new EventEmitter<void>();

  form!: FormGroup;
  submitting = false;

  readonly days = ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'];
  readonly grades = ['Grade 1','Grade 2','Grade 3','Grade 4','Grade 5','Grade 6','Grade 7','Grade 8','Grade 9','Grade 10','Grade 11','Grade 12'];
  courses: any[] = [];
  selectedCourse: any = null;
  scheduleConflicts: any[] = [];
  checkingConflicts = false;

  constructor(
    private fb: FormBuilder, 
    private courseService: CourseService,
    private groupService: GroupService,
    private toastService: ToastService,
    private confirmation: ConfirmationService,
    private router: Router,
    private translate: TranslateService
  ) {}

  ngOnInit(): void {
    // Initialize form with default values
    this.form = this.fb.group({
      name: [{value: '', disabled: true}], // Auto-generated, disabled like code
      code: [{value: '', disabled: true}], // Auto-generated, not required
      course: ['', [Validators.required]],  // Required field
      gradeLevel: ['Grade 9', [Validators.required]],
      schedule: this.fb.array([this.createScheduleSlot()]),
      pricePerSession: [0, [Validators.min(0)]]
    });

    // Load courses with teacher and subject info
    this.loadCourses();

    // Watch for course changes to update selected course and check conflicts
    this.form.get('course')?.valueChanges.pipe(distinctUntilChanged()).subscribe((courseId) => {
      this.selectedCourse = this.courses.find(c => c._id === courseId);
      this.autoGenerateGroupName();
      this.checkScheduleConflicts();
    });
    
    // Watch for grade level changes to auto-generate name
    this.form.get('gradeLevel')?.valueChanges.pipe(distinctUntilChanged()).subscribe(() => {
      this.autoGenerateGroupName();
    });
    
    // Watch for schedule changes to check for conflicts and update name
    this.form.get('schedule')?.valueChanges.pipe(debounceTime(500)).subscribe(() => {
      this.autoGenerateGroupName();
      this.checkScheduleConflicts();
    });
    
    // Populate form if initialValue is already available
    if (this.initialValue && Object.keys(this.initialValue).length > 0) {
      this.updateFormValues();
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    // Update form when initialValue changes (async data loading)
    if (changes['initialValue'] && this.form && changes['initialValue'].currentValue) {
      const current = changes['initialValue'].currentValue;
      if (current && Object.keys(current).length > 0) {
        this.updateFormValues();
      }
    }
  }

  private loadCourses(): void {
    this.courseService.getCourses({ page: 1, limit: 100 }).subscribe({
      next: res => {
        if (res.success) {
          // Handle different response structures
          if (res.data && (res.data as any).courses) {
            this.courses = (res.data as any).courses;
          } else if (Array.isArray(res.data)) {
            this.courses = res.data;
          } else {
            this.courses = [];
          }
          
          console.log('Loaded courses:', this.courses.length);
          
          // If we have initial data, update selected course
          const initialCourseId = this.initialValue?.course?._id || this.initialValue?.course;
          if (initialCourseId && this.courses.length > 0) {
            this.selectedCourse = this.courses.find(c => c._id === initialCourseId);
            console.log('Selected course:', this.selectedCourse);
          }
        } else {
          this.courses = [];
        }
      },
      error: err => { 
        console.error('Failed to load courses:', err); 
        this.courses = []; 
        this.toastService.error(this.translate.instant('groups.failedToLoadCourses'));
      }
    });
  }

  private createScheduleSlot(slot?: any): FormGroup {
    return this.fb.group({
      day: [slot?.day || 'saturday', Validators.required],
      startTime: [slot?.startTime || '10:00', Validators.required],
      endTime: [slot?.endTime || '12:00', Validators.required]
    });
  }

  private updateFormValues(): void {
    if (!this.initialValue) return;
    
    // Extract course ID
    const courseId = this.initialValue.course?._id || this.initialValue.course || '';
    
    // Update basic form fields (don't set name, it will be auto-generated)
    this.form.patchValue({
      code: this.initialValue.code || '',
      course: courseId,
      gradeLevel: this.initialValue.gradeLevel || 'Grade 9',
      pricePerSession: this.initialValue.pricePerSession ?? 0
    });
    
    // Update schedule array
    if (this.initialValue.schedule && Array.isArray(this.initialValue.schedule) && this.initialValue.schedule.length > 0) {
      const scheduleArray = this.form.get('schedule') as FormArray;
      scheduleArray.clear();
      this.initialValue.schedule.forEach((slot: any) => {
        scheduleArray.push(this.createScheduleSlot(slot));
      });
    }
    
    // Update selected course if courses are already loaded
    if (courseId && this.courses.length > 0) {
      this.selectedCourse = this.courses.find(c => c._id === courseId);
    }
    
    // Auto-generate the name based on course, grade, and schedule
    // This ensures the name is always current in edit mode
    this.autoGenerateGroupName();
  }

  get schedule(): FormArray { return this.form.get('schedule') as FormArray; }
  addSlot(): void { this.schedule.push(this.createScheduleSlot()); }
  removeSlot(i: number): void { this.schedule.removeAt(i); }

  autoGenerateGroupName(): void {
    // Get the required data
    const course = this.selectedCourse;
    const gradeLevel = this.form.get('gradeLevel')?.value;
    const scheduleArray = this.form.get('schedule')?.value || [];
    
    // Check if we have enough data to generate a name
    if (!course || !course.subject || !gradeLevel || scheduleArray.length === 0) {
      return;
    }
    
    // Extract subject name
    const subjectName = course.subject.name || 'Subject';
    
    // Get unique days from schedule (abbreviated: Sat, Mon, etc.)
    const dayAbbreviations: { [key: string]: string } = {
      'monday': 'Mon',
      'tuesday': 'Tue',
      'wednesday': 'Wed',
      'thursday': 'Thu',
      'friday': 'Fri',
      'saturday': 'Sat',
      'sunday': 'Sun'
    };
    
    const uniqueDays = [...new Set(scheduleArray.map((slot: any) => slot.day))];
    const daysList = uniqueDays
      .map((day: any) => dayAbbreviations[day.toLowerCase()] || day)
      .join('/');
    
    // Generate the name: "Subject - Grade - Days"
    const generatedName = `${subjectName} - ${gradeLevel} - ${daysList}`;
    
    // Always update the name field (it's disabled, so user can't edit it anyway)
    this.form.patchValue({ name: generatedName }, { emitEvent: false });
  }

  checkScheduleConflicts(): void {
    const courseId = this.form.get('course')?.value;
    const schedule = this.form.get('schedule')?.value;

    if (!courseId || !schedule || schedule.length === 0) {
      this.scheduleConflicts = [];
      return;
    }

    // Validate schedule times
    const hasInvalidSchedule = schedule.some((slot: any) => 
      !slot.day || !slot.startTime || !slot.endTime
    );
    
    if (hasInvalidSchedule) {
      this.scheduleConflicts = [];
      return;
    }

    this.checkingConflicts = true;
    const excludeGroupId = this.initialValue?._id || this.initialValue?.id;

    this.groupService.checkScheduleConflict(courseId, schedule, excludeGroupId).subscribe({
      next: (response: any) => {
        this.checkingConflicts = false;
        if (response.success && response.data) {
          this.scheduleConflicts = response.data.conflicts || [];
          
          if (this.scheduleConflicts.length > 0) {
            this.toastService.warning(
              this.translate.instant('groups.scheduleConflictDetectedToast', { count: this.scheduleConflicts.length }),
              this.translate.instant('groups.scheduleConflictTitle'),
              5000
            );
          }
        }
      },
      error: (error: any) => {
        this.checkingConflicts = false;
        console.error('Failed to check schedule conflicts:', error);
      }
    });
  }

  async submit(): Promise<void> {
    if (this.form.invalid) return;
    
    if (this.scheduleConflicts.length > 0) {
      const conflictList = this.scheduleConflicts
        .map(c => `• ${c.groupName} (${c.groupCode}) - ${c.day}: ${c.time}`)
        .join('\n');
      
      const confirmed = await this.confirmation.confirm({
        title: this.translate.instant('groups.scheduleConflictWarning'),
        message: this.translate.instant('groups.scheduleConflictsMessage', { count: this.scheduleConflicts.length, conflictList }),
        confirmText: this.translate.instant('groups.yesProceed'),
        cancelText: this.translate.instant('groups.noCancel'),
        type: 'warning'
      });
      
      if (!confirmed) return;
    }
    
    this.submitting = true;
    // Use getRawValue() to include disabled fields (name and code)
    this.save.emit(this.form.getRawValue());
  }

  goBack(): void { this.router.navigate(['/dashboard/groups']); }
}


